// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtoav3OGtrlnV5tUOaHPa73GvGxcqxwh4',
    appId: '1:495272599413:web:e53e086e90e138f37bfd3c',
    messagingSenderId: '495272599413',
    projectId: 'ritual-app-asis',
    authDomain: 'ritual-app-asis.firebaseapp.com',
    storageBucket: 'ritual-app-asis.firebasestorage.app',
    measurementId: 'G-N704VL6ESB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkym-M77rKxtPll-Y-u43uC9RUx4nVlA0',
    appId: '1:495272599413:android:33789bf6e355c3f37bfd3c',
    messagingSenderId: '495272599413',
    projectId: 'ritual-app-asis',
    storageBucket: 'ritual-app-asis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAScpm1P-FGRxflMB8lRLN-nECJAZ9LP4w',
    appId: '1:495272599413:ios:5417d7fac4fea9537bfd3c',
    messagingSenderId: '495272599413',
    projectId: 'ritual-app-asis',
    storageBucket: 'ritual-app-asis.firebasestorage.app',
    iosBundleId: 'com.example.ritual',
  );

}